# Generated by Django 5.0.1 on 2024-02-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounted', '0002_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
