# Generated by Django 5.0.1 on 2024-02-22 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_delete_addpaymentmethod_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
