# Generated by Django 5.0.1 on 2024-02-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
